sudo: true

dist: jessie

env:
  global:
    secure: "gJMILv803Mgt6zK2+6i2z5RET9zeV4JCeAjYjIsrbIkcabBI81e7imGn7kXFPCjHahjoPXVWJYn60XbyvGVn4hhUH5CUskTiGdux/DCxRQgBvXTdh5ucW9rGt0bj24KUtuMxscXcMHU95q56ozWQD/9jM+2JW/Msc8x0VMHXeO35hfgc/GifjtMjQHKP5K+D82OJLhSFdorRcFwZlra0GFhUxtcnnsvbHtzsENV2F02XtZCqWg3Wt16+bISZbN4tvJ8m4fs18WTvAskTKzy/MTCeuUK+IrSk8sjcPytzzgMlb2lNNIqESiQp7XLY/+diMxRAGQ1cz0QGglEV3FVmwyEDRc+71Yxz2733W60swVqKeAXAQMvZhWzSdNPY/3dXogkiRkchcZQV2S09imAqmz8aR+2xSjy8BjeL3IAjaUssMDjKrbEqiIMR9DRM11JNIceqENgMwwfUT3LjXHrp8KrUbcNcAJq86U67V5Qk2eR07Op2OPMTU8YIb0acHGQ4TBk/N3Q9niW3sxTmQJI49CmDkc9MeFHLmL265Qsu+aooi517KO/EMryXOOABLTusubIKBbSaRtaxYdZVqmeZ59Nf44OxKhFrqcb1DaAJxevEp4u8/BcvGzUYVIjtdvTUGmgYidkxvatV00jgGE3+BXLJw0ThumleIk7yy7M8S4E="

branches:
  only:
    - 'master'

addons:
  apt:
    packages:
      - openssl
      - git-core

git:
  submodules: false

before_install: |
  git remote set-url origin git@github.com:${TRAVIS_REPO_SLUG}.git
  # change to last commit author
  git config user.name \
    "$(git --no-pager show -s --format='%an' HEAD~1)"
  git config user.email \
    "$(git --no-pager show -s --format='%ae' HEAD~1)"

install: |
  mkdir -p ~/.ssh && cp -v ${TRAVIS_BUILD_DIR}/.ssh/* ~/.ssh
  openssl rsa -in ~/.ssh/id_rsa.enc \
    -out ~/.ssh/id_rsa -passin pass:$SSHPASS
  chmod 600 ~/.ssh/id_rsa && unset GIT_SSH
  git submodule update --init --recursive
  # fetch latest test revision
  cd test && git pull origin master && cd ..

script: bash travmo.sh
